const mongoose = require('mongoose');

const TicketSchema = new mongoose.Schema({
  ticket_number: { type: String, required: true, unique: true },
  order_id: { type: String, required: true }, // Link to Order ID
  description: { type: String, required: true },
  image_url: { type: String },
  decision: { type: String }, // Decision generated by OpenAI
});

module.exports = mongoose.model('Ticket', TicketSchema);
