version: "3.1"
language: "en"

pipeline:
  - name: WhitespaceTokenizer
  - name: CountVectorsFeaturizer
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true

policies:
- name: "MemoizationPolicy"
- name: "TEDPolicy"
  max_history: 5
  epochs: 100
assistant_id: 20250101-153858-snowy-sugar
